dist: trusty
language: python
python:
    - 2.7

before_install:
    - sudo pip install pygments markdown docopt pyyaml
    - sudo python setup.py install

install:
    sudo pip install coveralls

before_script:
  - "echo 'starting'"

script:
    #sudo coverage run --include="mdv/markdownviewer.py"  setup.py test
    echo $PYTHONPATH && export PYTHONPATH="`pwd`" && python -c "import docopt, markdown, pygments, yaml" && python mdv/tests/test_files.py

after_success:
    coveralls

