dist: trusty
language: python
python:
    - 2.7

before_install:
    - sudo pip install pygments markdown docopt pyyaml
    - sudo python setup.py install

before_script:
  - "echo 'starting'"

script: "./tests/run test"

