dist: trusty
language: python
python:
    - 2.7

before_install:
    - sudo pip install pygments markdown docopt pyyaml
    - sudo python setup.py install

install:
    pip install coveralls

before_script:
  - "echo 'starting'"

script:
    sudo coverage run --source=mdv setup.py test

after_success:
    coveralls

